name: Publish Electron App

on:
  workflow_dispatch:
    inputs:
      gpu:
        description: "GPU variant to publish (cuda, rocm, jetpack5, jetpack6, all)"
        required: false
        default: all

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-26
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.TEAM_ID }}
      CSC_INSTALLER_LINK: ${{ secrets.CSC_INSTALLER_LINK }}
      CSC_INSTALLER_KEY_PASSWORD: ${{ secrets.CSC_INSTALLER_KEY_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: src
        run: npm ci && npm install -g typescript

      - name: Build and publish CPU Electron app (macOS ARM)
        working-directory: src
        run: npm run publish

      - name: Verify macOS identity
        working-directory: src
        run: |
          ditto -x -k dist/*.zip dist/unzipped
          codesign -vvv --strict dist/unzipped/*.app

  build-macos-x86:
    runs-on: macos-15-intel
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.TEAM_ID }}
      CSC_INSTALLER_LINK: ${{ secrets.CSC_INSTALLER_LINK }}
      CSC_INSTALLER_KEY_PASSWORD: ${{ secrets.CSC_INSTALLER_KEY_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: src
        run: npm ci && npm install -g typescript

      - name: Build and publish CPU Electron app (macOS x86)
        working-directory: src
        run: npm run publish

      - name: Verify macOS identity
        working-directory: src
        run: |
          ditto -x -k dist/*.zip dist/unzipped
          codesign -vvv --strict dist/unzipped/*.app

  build-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src

  build-windows-arm:
    runs-on: windows-11-arm
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src

  build-linux:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src

  build-linux-arm:
    runs-on: ubuntu-24.04-arm
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src

  build-windows-cuda:
    if: ${{ github.event.inputs.gpu == 'cuda' || github.event.inputs.gpu == 'all' }}
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OLLAMA_ACCELERATION: "cuda"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src

  build-linux-cuda:
    if: ${{ github.event.inputs.gpu == 'cuda' || github.event.inputs.gpu == 'all' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OLLAMA_ACCELERATION: "cuda"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src
  build-windows-rocm:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OLLAMA_ACCELERATION: "rocm"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src
  build-linux-rocm:
    if: ${{ github.event.inputs.gpu == 'rocm' || github.event.inputs.gpu == 'all' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OLLAMA_ACCELERATION: "rocm"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src
  build-linux-arm-cuda:
    runs-on: ubuntu-24.04-arm
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OLLAMA_ACCELERATION: "cuda"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src

  build-linux-jetpack5:
    if: ${{ github.event.inputs.gpu == 'jetpack5' || github.event.inputs.gpu == 'all' }}
    runs-on: ubuntu-24.04-arm
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OLLAMA_ACCELERATION: "jetpack5"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src

  build-linux-jetpack6:
    if: ${{ github.event.inputs.gpu == 'jetpack6' || github.event.inputs.gpu == 'all' }}
    runs-on: ubuntu-24.04-arm
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OLLAMA_ACCELERATION: "jetpack6"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - run: npm ci && npm install -g typescript
        working-directory: src
      - run: npm run publish
        working-directory: src
